#!/usr/bin/env bash
GEM_LOC=$(bundle info --path ecosystem-components-library)
echo "Linking $GEM_LOC"
ln -sfn $GEM_LOC bookshop_gem

npm install

npm run bookshop-live

echo "📚 ✅ : Prebuild script finished"